# Generated by Django 4.2.4 on 2023-08-27 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_count', models.IntegerField(editable=False)),
                ('average_word_size', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', related_query_name='post', to='posts.post')),
            ],
            options={
                'db_table': 'post_has_analysis',
            },
        ),
    ]
